on:
  push:
    branches:
    - master
name: Push Event
jobs:
  test:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm run build
      - run: npm run deploy
